export const POST_USER_BEGIN = "POST_USER_BEGIN";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_FAIL = "POST_USER_FAIL";

// export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
// export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
// export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
