export const POST_USER_BEGIN = "POST_USER_BEGIN";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_FAIL = "POST_USER_FAIL";

// export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
// export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
// export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

// GET_USER_BEGIN, GET_USER_SUCESS, GET_USER_FAIL

export const LOADING_USER = "LOADING_USER";

export const SET_AUTH = "SET_AUTH";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const GET_AUTHENTICATED_USER = "GET_AUTHENTICATED_USER";

export const POKA_ERRORA = "POKA_ERRORA";
